version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
  spark-worker-1:
    image: bde2020/spark-worker:3.1.2-hadoop3.2
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    wine-prediction-test:
      image: rimpal1/wine-quality-pred
      container_name: wine-quality-pred-test
      depends_on:
        - spark-master
        - spark-worker-1
      volumes:
        - /tmp/spark-events-local:/tmp/spark-events
